#!/usr/bin/env python

import sys
from optparse import OptionParser

from systematic.osx.timecapsule import *

LOGFORMAT = '%(levelname)s %(message)s'

parser = OptionParser()
parser.set_usage('%s <mount|umount|status> <diskname|all>' % sys.argv[0])
parser.set_defaults(**{'config':None})
parser.add_option('-l','--list',dest='list',action='store_true',help='List configured shares')
parser.add_option('-c','--config',dest='config',help='Alternative configuration file')
parser.add_option('-v','--verbose',dest='verbose',action='store_true',help='Verbose messages')
parser.add_option('-d','--debug',dest='debug',action='store_true',help='Show debug messages')
(options,args) = parser.parse_args()
if options.verbose: 
    logging.basicConfig(level=logging.INFO,format=LOGFORMAT)
if options.debug: 
    logging.basicConfig(level=logging.DEBUG,format=LOGFORMAT)

try:
    config = TimeCapsuleConfig(options.config)
except TimeCapsuleError,e:
    print 'ERROR: %s' % e
    sys.exit(1)

if options.list:
    logging.info('List of configured disks in file %s' % config.path)
    for d in config.disks:
        print d
    sys.exit(0)

if len(args) < 2:
    print parser.get_usage()
    sys.exit(1)

if args[0] == 'option':
    try:
        print config.__getattr__(args[1])
        sys.exit(0)
    except AttributeError,e:
        print e
        sys.exit(1)

if args[0] not in ['mount','umount','status','mountpoint']:
    print parser.get_usage()
    sys.exit(1)

try:
    if args[1] == 'all':
        disks = config.disks
    else:
        disks = [config[args[1]]]
except TimeCapsuleError,e:
    print 'Error initalizing disk configs: %s' % e
    sys.exit(1)
except KeyError,e:
    print str(e).strip("'")
    sys.exit(1)

for d in disks:
    try:
        if args[0] == 'mount': 
            logging.info('Mounting: %s' % d)
            d.mount()
        elif args[0] == 'umount': 
            logging.info('Unmounting: %s' % d)
            d.umount()
        elif args[0] == 'mountpoint': 
            print d.mountpoint
        else: 
            print '%s: %s' % (d.name,d.status())
    except TimeCapsuleError,e:
        print '%s: %s' % (d.name,e)
        continue

sys.exit(0)
